import {mkdir,writeFile} from 'node:fs/promises';import {existsSync} from 'node:fs';import path from 'node:path';
const root='public/assets';await mkdir(root,{recursive:true});for(const d of ['agents','maps','roles','ranks'])await mkdir(path.join(root,d),{recursive:true});
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const get=async url=>(await fetch(url)).json();const save=async(url,file)=>{if(!url||existsSync(file))return;const r=await fetch(url);if(r.ok)await writeFile(file,Buffer.from(await r.arrayBuffer()))};
let agents={data:[]},maps={data:[]},tiers={data:[]},seasons={data:[]};
try{[agents,maps,tiers,seasons]=await Promise.all([get('https://valorant-api.com/v1/agents?isPlayableCharacter=true&language=en-US'),get('https://valorant-api.com/v1/maps?language=en-US'),get('https://valorant-api.com/v1/competitivetiers?language=en-US'),get('https://valorant-api.com/v1/seasons?language=en-US').catch(()=>({data:[]}))])}catch(error){console.warn('Valorant API is unavailable; writing an empty fallback catalog.',error.message)}
const catalog={agents:{},maps:{},roles:{},ranks:{},seasons:seasons.data??[]};
for(const a of agents.data){const f=`agents/${slug(a.displayName)}.png`;await save(a.displayIcon,path.join(root,f));catalog.agents[a.displayName.toLowerCase()]={name:a.displayName,image:`/assets/${f}`};if(a.role){const rf=`roles/${slug(a.role.displayName)}.png`;await save(a.role.displayIcon,path.join(root,rf));catalog.roles[a.role.displayName.toLowerCase()]={name:a.role.displayName,image:`/assets/${rf}`}}}
for(const m of maps.data){const f=`maps/${slug(m.displayName)}.jpg`;await save(m.listViewIconTall??m.splash??m.displayIcon,path.join(root,f));catalog.maps[m.displayName.toLowerCase()]={name:m.displayName,image:`/assets/${f}`}}
const latest=tiers.data.at(-1)?.tiers??[];for(const t of latest){if(!t.tierName||t.tierName==='Unused1'||t.tierName==='Unused2')continue;const f=`ranks/${slug(t.tierName)}.png`;await save(t.largeIcon??t.smallIcon,path.join(root,f));catalog.ranks[t.tierName.toLowerCase()]={name:t.tierName,image:`/assets/${f}`,order:t.tier}}
await writeFile(path.join(root,'catalog.json'),JSON.stringify(catalog,null,2));console.log(`Saved ${Object.keys(catalog.agents).length} agents, ${Object.keys(catalog.maps).length} maps, ${Object.keys(catalog.roles).length} roles and ${Object.keys(catalog.ranks).length} ranks.`)
